# .github/workflows/note-link-janitor.yml

name: Note Link Janitor

on:
  gollum:
  workflow_dispatch:

jobs:
  update:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
      - uses: sander/note-link-janitor@v5